Update hikami-firstboot
Add the ability to remove system flatpaks
Add --verbose to all flatpak commands for better debugging

diff --git a/hikami-firstboot b/hikami-firstboot
--- a/hikami-firstboot
+++ b/hikami-firstboot
@@ -48,18 +48,33 @@ PASSWD="$(zenity --password)\n" # Password Box
     until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
     echo "00"
 
+    if zenity --question --title="Remove system apps?" --text="Do you want to remove existing Flatpak system apps?\n\n
+NOTE: This is HIGHLY recommended! Any Flatpak system apps that are kept won't get any updates!" --ok-label="Yes" --cancel-label="No (NOT RECOMMENDED)"
+    then
+        echo "# Removing system Flatpaks"
+        echo -e $PASSWD | sudo flatpak remove --system --all --verbose --noninteractive
+        if [ "$?" != 0 ]; then zenity --error --text="Removing system Flatpaks failed"; exit 1; fi
+        mkdir -p "$HOME"/.config/hikami/
+        touch "$HOME"/.config/hikami/system-apps-removed
+        rm "$HOME"/.config/hikami/system-apps-not-removed
+    else
+        mkdir -p "$HOME"/.config/hikami/
+        touch "$HOME"/.config/hikami/system-apps-not-removed
+        rm "$HOME"/.config/hikami/system-apps-removed
+    fi
+
     echo "# Removing Filtered Flathub Repository"
-    echo -e $PASSWD | sudo -S flatpak remote-delete flathub --force ||:
+    echo -e $PASSWD | sudo -S flatpak remote-delete flathub --force --verbose ||:
     if [ "$?" != 0 ]; then zenity --error --text="Removing Filtered Flatpak repo failed"; exit 1; fi
     echo "3"
 
     echo "# Removing Fedora Flatpak Repository"
-    echo -e $PASSWD | sudo -S flatpak remote-delete fedora --force ||:
+    echo -e $PASSWD | sudo -S flatpak remote-delete fedora --force --verbose ||:
     if [ "$?" != 0 ]; then zenity --error --text="Removing Fedora Flatpak repo failed"; exit 1; fi
     echo "5"
 
     echo "# Enabling Flathub Repository"
-    flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+    flatpak remote-add --user --if-not-exists --verbose flathub https://flathub.org/repo/flathub.flatpakrepo
     if [ "$?" != 0 ]; then zenity --error --text="Adding Flathub repo failed"; exit 1; fi
     echo "7"
 
@@ -68,20 +83,20 @@ PASSWD="$(zenity --password)\n" # Password Box
 Librewolf, ONLYOFFICE, Atoms (with Distrobox support enabled), Extension Manager, Flatseal and Celluloid Media Player"
     then 
         echo "# Installing LibreWolf"
-        flatpak install --user --noninteractive flathub io.gitlab.librewolf-community
+        flatpak install --user --noninteractive --verbose flathub io.gitlab.librewolf-community
         if [ "$?" != 0 ]; then zenity --error --text="Installing LibreWolf failed"; exit 1; fi
         echo "20"
 
         echo "# Installing ONLYOFFICE"
-        flatpak install --user --noninteractive flathub org.onlyoffice.desktopeditors
+        flatpak install --user --noninteractive --verbose flathub org.onlyoffice.desktopeditors
         if [ "$?" != 0 ]; then zenity --error --text="Installing ONLYOFFICE failed"; exit 1; fi
         echo "30"
 
         echo "# Installing Atoms"
-        flatpak install --user --noninteractive flathub pm.mirko.Atoms
+        flatpak install --user --noninteractive --verbose flathub pm.mirko.Atoms
         if [ "$?" != 0 ]; then zenity --error --text="Installing Atoms failed"; exit 1; fi
         echo "# Adding override for Atoms"
-        flatpak override --user --talk-name=org.freedesktop.Flatpak pm.mirko.Atoms
+        flatpak override --user --verbose --talk-name=org.freedesktop.Flatpak pm.mirko.Atoms
         if [ "$?" != 0 ]; then zenity --error --text="Adding override for Atoms failed"; exit 1; fi
         echo "# Make config folder for Atoms"
         mkdir -p "$HOME/.var/app/pm.mirko.Atoms/config/glib-2.0/settings"
@@ -92,17 +107,17 @@ Librewolf, ONLYOFFICE, Atoms (with Distrobox support enabled), Extension Manager
         echo "35"
 
         echo "# Installing Extension Manager"
-        flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager
+        flatpak install --user --noninteractive --verbose flathub com.mattjakeman.ExtensionManager
         if [ "$?" != 0 ]; then zenity --error --text="Installing Extension Manager failed"; exit 1; fi
         echo "40"
 
         echo "# Installing Flatseal"
-        flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
+        flatpak install --user --noninteractive --verbose flathub com.github.tchx84.Flatseal
         if [ "$?" != 0 ]; then zenity --error --text="Installing Flatseal failed"; exit 1; fi
         echo "45"
 
         echo "# Installing Celluloid Media Player"
-        flatpak install --user --noninteractive flathub io.github.celluloid_player.Celluloid
+        flatpak install --user --noninteractive --verbose flathub io.github.celluloid_player.Celluloid
         if [ "$?" != 0 ]; then zenity --error --text="Installing Celluloid failed"; exit 1; fi
         echo "50"
     else
@@ -113,52 +128,52 @@ Librewolf, ONLYOFFICE, Atoms (with Distrobox support enabled), Extension Manager
 Calculator, Document Viewer (Evince), Logs, Nautilus Previewer (Sushi), Text Editor, Weather, Disk Usage Analyzer (baobab), Image Viewer (eog), Font Manager and File Roller."
     then
         echo "# Installing GNOME Calculator"
-        flatpak install --user --noninteractive flathub org.gnome.Calculator
+        flatpak install --user --noninteractive --verbose flathub org.gnome.Calculator
         if [ "$?" != 0 ]; then zenity --error --text="Installing GNOME Calculator failed"; exit 1; fi
         echo "53"
 
         echo "# Installing GNOME Document Viewer"
-        flatpak install --user --noninteractive flathub org.gnome.Evince
+        flatpak install --user --noninteractive --verbose flathub org.gnome.Evince
         if [ "$?" != 0 ]; then zenity --error --text="Installing GNOME Document Viewer failed"; exit 1; fi
         echo "56"
 
         echo "# Installing GNOME Logs"
-        flatpak install --user --noninteractive flathub org.gnome.Logs
+        flatpak install --user --noninteractive --verbose flathub org.gnome.Logs
         if [ "$?" != 0 ]; then zenity --error --text="Installing GNOME Logs failed"; exit 1; fi
         echo "59"
 
         echo "# Installing GNOME Nautilus Previewer"
-        flatpak install --user --noninteractive flathub org.gnome.NautilusPreviewer
+        flatpak install --user --noninteractive --verbose flathub org.gnome.NautilusPreviewer
         if [ "$?" != 0 ]; then zenity --error --text="Installing GNOME Nautilus Previewer failed"; exit 1; fi
         echo "62"
 
         echo "# Installing GNOME Text Editor"
-        flatpak install --user --noninteractive flathub org.gnome.TextEditor
+        flatpak install --user --noninteractive --verbose flathub org.gnome.TextEditor
         if [ "$?" != 0 ]; then zenity --error --text="Installing GNOME Text Editor failed"; exit 1; fi
         echo "65"
 
         echo "# Installing GNOME Weather"
-        flatpak install --user --noninteractive flathub org.gnome.Weather
+        flatpak install --user --noninteractive --verbose flathub org.gnome.Weather
         if [ "$?" != 0 ]; then zenity --error --text="Installing GNOME Weather failed"; exit 1; fi
         echo "68"
 
         echo "# Installing GNOME Disk Usage Analyzer"
-        flatpak install --user --noninteractive flathub org.gnome.baobab
+        flatpak install --user --noninteractive --verbose flathub org.gnome.baobab
         if [ "$?" != 0 ]; then zenity --error --text="Installing GNOME Disk Usage Analyzer failed"; exit 1; fi
         echo "71"
 
         echo "# Installing GNOME Image Viewer"
-        flatpak install --user --noninteractive flathub org.gnome.eog
+        flatpak install --user --noninteractive --verbose flathub org.gnome.eog
         if [ "$?" != 0 ]; then zenity --error --text="Installing GNOME Image Viewer failed"; exit 1; fi
         echo "74"
 
         echo "# Installing GNOME Font Manager"
-        flatpak install --user --noninteractive flathub org.gnome.FontManager
+        flatpak install --user --noninteractive --verbose flathub org.gnome.FontManager
         if [ "$?" != 0 ]; then zenity --error --text="Installing GNOME Font Manager failed"; exit 1; fi
         echo "77"
 
         echo "# Installing GNOME File Roller"
-        flatpak install --user --noninteractive flathub org.gnome.FileRoller
+        flatpak install --user --noninteractive --verbose flathub org.gnome.FileRoller
         if [ "$?" != 0 ]; then zenity --error --text="Installing GNOME File Roller failed"; exit 1; fi
         echo "80"
     else
@@ -197,7 +212,7 @@ NOTE: There will be a popup for every extension asking you to install them, just
     mkdir -p "$HOME"/.config/hikami/
     touch "$HOME"/.config/hikami/firstboot-done
     gnome-extensions disable background-logo@fedorahosted.org
-    flatpak install --user --noninteractive flathub org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark
+    flatpak install --user --noninteractive --verbose flathub org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark
     if [ "$?" != 0 ]; then zenity --error --text="Installing adw-gtk3 Flatpak failed"; exit 1; fi
 
     if zenity --question --title="Select Color Scheme" --text="Do you want a light theme or a dark theme?" --ok-label="Dark Theme" --cancel-label="Light Theme"
